routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend
 */

// Switch between the included languages
Route::get('lang/{lang}', 'LanguageController@swap');

/* ----------------------------------------------------------------------- */

/**
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
	require (__DIR__ . '/Frontend/Frontend.php');
	require (__DIR__ . '/Frontend/Access.php');
});

/* ----------------------------------------------------------------------- */

/**
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
	/**
	 * These routes need view-backend permission
	 * (good if you want to allow more than one group in the backend,
	 * then limit the backend features by different roles or permissions)
	 *
	 * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
	 */
	require (__DIR__ . '/Backend/Dashboard.php');
	require (__DIR__ . '/Backend/Search.php');
	require (__DIR__ . '/Backend/Access.php');
    require (__DIR__ . '/Backend/LogViewer.php');
    require (__DIR__ . '/Backend/Drivers.php');
    require (__DIR__ . '/Backend/Activities.php');
});

app/Models/TransicsActivity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TransicsActivity extends Model
{
    protected $fillable = ['transics_id', 'type', 'name', 'is_planning', 'color'];
    
    protected $casts = [
        'is_planning' => 'bool'
    ];
    
    public function getColorIconAttribute()
    {
        return '<i style="color: '.$this->color.'" class="fa fa-square"></i>';
    }
    
    public function getPlannableAttribute()
    {
        $icon = '<i class="fa fa-';
        $icon .= ($this->is_planning) ? 'check' : 'lock';
        return $icon . '"></i>';
    }
}

app/Http/Controllers/Backend/Access/Role/RoleController.php
<?php

namespace App\Http\Controllers\Backend\Access\Role;

use App\Models\Access\Role\Role;
use App\Http\Controllers\Controller;
use App\Repositories\Backend\Access\Role\RoleRepository;
use App\Http\Requests\Backend\Access\Role\StoreRoleRequest;
use App\Http\Requests\Backend\Access\Role\ManageRoleRequest;
use App\Http\Requests\Backend\Access\Role\UpdateRoleRequest;
use App\Repositories\Backend\Access\Permission\PermissionRepository;

/**
 * Class RoleController
 * @package App\Http\Controllers\Access
 */
class RoleController extends Controller
{
    /**
     * @var RoleRepository
     */
    protected $roles;

    /**
     * @var PermissionRepository
     */
    protected $permissions;

    /**
     * @param RoleRepository       $roles
     * @param PermissionRepository $permissions
     */
    public function __construct(RoleRepository $roles, PermissionRepository $permissions)
	{
        $this->roles = $roles;
        $this->permissions = $permissions;
    }

	/**
	 * @param ManageRoleRequest $request
	 * @return mixed
	 */
	public function index(ManageRoleRequest $request)
	{
        return view('backend.access.roles.index');
    }

    /**
     * @param ManageRoleRequest $request
     * @return mixed
     */
    public function create(ManageRoleRequest $request)
    {
        return view('backend.access.roles.create')
            ->withPermissions($this->permissions->getAll())
			->withRoleCount($this->roles->getCount());
    }

    /**
     * @param  StoreRoleRequest $request
     * @return mixed
     */
    public function store(StoreRoleRequest $request)
    {
        $this->roles->create($request->all());
        return redirect()->route('admin.access.role.index')->withFlashSuccess(trans('alerts.backend.roles.created'));
    }

    /**
     * @param  Role $role
     * @param  ManageRoleRequest $request
     * @return mixed
     */
    public function edit(Role $role, ManageRoleRequest $request)
    {
        return view('backend.access.roles.edit')
            ->withRole($role)
            ->withRolePermissions($role->permissions->pluck('id')->all())
            ->withPermissions($this->permissions->getAll());
    }

    /**
     * @param  Role $role
     * @param  UpdateRoleRequest $request
     * @return mixed
     */
    public function update(Role $role, UpdateRoleRequest $request)
    {
        $this->roles->update($role, $request->all());
        return redirect()->route('admin.access.role.index')->withFlashSuccess(trans('alerts.backend.roles.updated'));
    }

    /**
     * @param  Role $role
     * @param  ManageRoleRequest $request
     * @return mixed
     */
    public function destroy(Role $role, ManageRoleRequest $request)
    {
        $this->roles->delete($role);
        return redirect()->route('admin.access.role.index')->withFlashSuccess(trans('alerts.backend.roles.deleted'));
    }
}

app/Http/Controllers/Backend/Access/Role/RoleTableController.php
<?php

namespace App\Http\Controllers\Backend\Access\Role;

use App\Http\Controllers\Controller;
use Yajra\Datatables\Facades\Datatables;
use App\Repositories\Backend\Access\Role\RoleRepository;
use App\Http\Requests\Backend\Access\Role\ManageRoleRequest;

/**
 * Class RoleTableController
 * @package App\Http\Controllers\Access
 */
class RoleTableController extends Controller
{
	/**
	 * @var RoleRepository
	 */
	protected $roles;

	/**
	 * @param RoleRepository       $roles
	 */
	public function __construct(RoleRepository $roles)
	{
		$this->roles = $roles;
	}

	/**
	 * @param ManageRoleRequest $request
	 * @return mixed
	 */
	public function __invoke(ManageRoleRequest $request)
	{
		return Datatables::of($this->roles->getForDataTable())
			->addColumn('permissions', function($role) {
				if ($role->all)
					return '<span class="label label-success">' . trans('labels.general.all') . '</span>';

				return $role->permissions->count() ?
					implode("<br/>", $role->permissions->pluck('display_name')->toArray()) :
					'<span class="label label-danger">' . trans('labels.general.none') . '</span>';
			})
			->addColumn('users', function($role) {
				return $role->users->count();
			})
			->addColumn('actions', function($role) {
				return $role->action_buttons;
			})
			->make(true);
	}
}

app/Http/Controllers/Backend/Access/User/UserAccessController.php
<?php

namespace App\Http\Controllers\Backend\Access\User;

use App\Helpers\Auth\Auth;
use App\Models\Access\User\User;
use App\Http\Controllers\Controller;
use App\Exceptions\GeneralException;
use App\Http\Requests\Backend\Access\User\ManageUserRequest;

/**
 * Class UserAccessController
 */
class UserAccessController extends Controller
{

	/**
	 * @param User $user
	 * @param ManageUserRequest $request
	 * @return \Illuminate\Http\RedirectResponse
	 * @throws GeneralException
	 */
	public function loginAs(User $user, ManageUserRequest $request) {
		// Overwrite who we're logging in as, if we're already logged in as someone else.
		if (session()->has('admin_user_id') && session()->has('temp_user_id')) {
			// Let's not try to login as ourselves.
			if (access()->id() == $user->id || session()->get('admin_user_id') == $user->id) {
				throw new GeneralException('Do not try to login as yourself.');
			}

			// Overwrite temp user ID.
			session(['temp_user_id' => $user->id]);

			// Login.
			access()->loginUsingId($user->id);

			// Redirect.
			return redirect()->route("frontend.index");
		}

		app()->make(Auth::class)->flushTempSession();

		// Won't break, but don't let them "Login As" themselves
		if (access()->id() == $user->id) {
			throw new GeneralException("Do not try to login as yourself.");
		}

		// Add new session variables
		session(["admin_user_id" => access()->id()]);
		session(["admin_user_name" => access()->user()->name]);
		session(["temp_user_id" => $user->id]);

		// Login user
		access()->loginUsingId($user->id);

		// Redirect to frontend
		return redirect()->route("frontend.index");
	}
}

app/Http/Controllers/Backend/Access/User/UserConfirmationController.php
<?php

namespace App\Http\Controllers\Backend\Access\User;

use App\Models\Access\User\User;
use App\Http\Controllers\Controller;
use App\Notifications\Frontend\Auth\UserNeedsConfirmation;
use App\Http\Requests\Backend\Access\User\ManageUserRequest;

/**
 * Class UserConfirmationController
 */
class UserConfirmationController extends Controller
{

	/**
	 * @param User $user
	 * @param ManageUserRequest $request
	 * @return mixed
	 */
	public function sendConfirmationEmail(User $user, ManageUserRequest $request)
	{
		$user->notify(new UserNeedsConfirmation($user->confirmation_code));
		return redirect()->back()->withFlashSuccess(trans('alerts.backend.users.confirmation_email'));
	}
}

app/Http/Controllers/Backend/Access/User/UserController.php
<?php

namespace App\Http\Controllers\Backend\Access\User;

use App\Http\Requests\Backend\Access\User\StoreUserRequest;
use App\Models\Access\User\User;
use App\Http\Controllers\Controller;
use App\Repositories\Backend\Access\User\UserRepository;
use App\Repositories\Backend\Access\Role\RoleRepository;
use App\Http\Requests\Backend\Access\User\StoreDriverRequest;
use App\Http\Requests\Backend\Access\User\ManageUserRequest;
use App\Http\Requests\Backend\Access\User\UpdateUserRequest;

/**
 * Class UserController
 */
class UserController extends Controller
{
    /**
     * @var UserRepository
     */
    protected $users;

    /**
     * @var RoleRepository
     */
    protected $roles;

    /**
     * @param UserRepository $users
     * @param RoleRepository $roles
     */
    public function __construct(UserRepository $users, RoleRepository $roles)
    {
        $this->users = $users;
        $this->roles = $roles;
    }

	/**
     * @param ManageUserRequest $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(ManageUserRequest $request)
    {
        return view('backend.access.index');
    }

	/**
     * @param ManageUserRequest $request
     * @return mixed
     */
    public function create(ManageUserRequest $request)
    {
        return view('backend.access.create')
            ->withRoles($this->roles->getAll());
    }

	/**
     * @param StoreDriverRequest $request
     *
*@return mixed
     */
    public function store(StoreUserRequest $request)
    {
        $this->users->create(['data' => $request->except('assignees_roles'), 'roles' => $request->only('assignees_roles')]);
        return redirect()->route('admin.access.user.index')->withFlashSuccess(trans('alerts.backend.users.created'));
    }

	/**
	 * @param User $user
	 * @param ManageUserRequest $request
	 * @return mixed
	 */
	public function show(User $user, ManageUserRequest $request) {
		return view('backend.access.show')
			->withUser($user);
	}

	/**
     * @param User $user
     * @param ManageUserRequest $request
     * @return mixed
     */
    public function edit(User $user, ManageUserRequest $request)
    {
        return view('backend.access.edit')
            ->withUser($user)
            ->withUserRoles($user->roles->pluck('id')->all())
            ->withRoles($this->roles->getAll());
    }

	/**
     * @param User $user
     * @param UpdateUserRequest $request
     * @return mixed
     */
    public function update(User $user, UpdateUserRequest $request)
    {
        $this->users->update($user, ['data' => $request->except('assignees_roles'), 'roles' => $request->only('assignees_roles')]);
        return redirect()->route('admin.access.user.index')->withFlashSuccess(trans('alerts.backend.users.updated'));
    }

	/**
     * @param User $user
     * @param ManageUserRequest $request
     * @return mixed
     */
    public function destroy(User $user, ManageUserRequest $request)
    {
        $this->users->delete($user);
        return redirect()->route('admin.access.user.deleted')->withFlashSuccess(trans('alerts.backend.users.deleted'));
    }
}

app/Http/Controllers/Backend/Access/User/UserPasswordController.php
<?php

namespace App\Http\Controllers\Backend\Access\User;

use App\Models\Access\User\User;
use App\Http\Controllers\Controller;
use App\Repositories\Backend\Access\User\UserRepository;
use App\Http\Requests\Backend\Access\User\ManageUserRequest;
use App\Http\Requests\Backend\Access\User\UpdateUserPasswordRequest;

/**
 * Class UserPasswordController
 */
class UserPasswordController extends Controller
{
	/**
	 * @var UserRepository
	 */
	protected $users;

	/**
	 * @param UserRepository $users
	 */
	public function __construct(UserRepository $users)
	{
		$this->users = $users;
	}

	/**
	 * @param User $user
	 * @param ManageUserRequest $request
	 * @return mixed
	 */
	public function edit(User $user, ManageUserRequest $request)
	{
		return view('backend.access.change-password')
			->withUser($user);
	}

	/**
	 * @param User $user
	 * @param UpdateUserPasswordRequest $request
	 * @return mixed
	 */
	public function update(User $user, UpdateUserPasswordRequest $request)
	{
		$this->users->updatePassword($user, $request->all());
		return redirect()->route('admin.access.user.index')->withFlashSuccess(trans('alerts.backend.users.updated_password'));
	}
}

app/Http/Controllers/Backend/Access/User/UserStatusController.php
<?php

namespace App\Http\Controllers\Backend\Access\User;

use App\Models\Access\User\User;
use App\Http\Controllers\Controller;
use App\Repositories\Backend\Access\User\UserRepository;
use App\Http\Requests\Backend\Access\User\ManageUserRequest;

/**
 * Class UserStatusController
 */
class UserStatusController extends Controller
{
	/**
	 * @var UserRepository
	 */
	protected $users;

	/**
	 * @param UserRepository $users
	 */
	public function __construct(UserRepository $users)
	{
		$this->users = $users;
	}

	/**
	 * @param ManageUserRequest $request
	 * @return mixed
	 */
	public function getDeactivated(ManageUserRequest $request)
	{
		return view('backend.access.deactivated');
	}

	/**
	 * @param ManageUserRequest $request
	 * @return mixed
	 */
	public function getDeleted(ManageUserRequest $request)
	{
		return view('backend.access.deleted');
	}

	/**
	 * @param User $user
	 * @param $status
	 * @param ManageUserRequest $request
	 * @return mixed
	 */
	public function mark(User $user, $status, ManageUserRequest $request)
	{
		$this->users->mark($user, $status);
		return redirect()->route($status == 1 ? "admin.access.user.index" : "admin.access.user.deactivated")->withFlashSuccess(trans('alerts.backend.users.updated'));
	}

	/**
	 * @param User $deletedUser
	 * @param ManageUserRequest $request
	 * @return mixed
	 */
	public function delete(User $deletedUser, ManageUserRequest $request)
	{
		$this->users->forceDelete($deletedUser);
		return redirect()->route('admin.access.user.deleted')->withFlashSuccess(trans('alerts.backend.users.deleted_permanently'));
	}

	/**
	 * @param User $deletedUser
	 * @param ManageUserRequest $request
	 * @return mixed
	 */
	public function restore(User $deletedUser, ManageUserRequest $request)
	{
		$this->users->restore($deletedUser);
		return redirect()->route('admin.access.user.index')->withFlashSuccess(trans('alerts.backend.users.restored'));
	}
}

app/Http/Controllers/Backend/Access/User/UserTableController.php
<?php

namespace App\Http\Controllers\Backend\Access\User;

use App\Http\Controllers\Controller;
use Yajra\Datatables\Facades\Datatables;
use App\Repositories\Backend\Access\User\UserRepository;
use App\Http\Requests\Backend\Access\User\ManageUserRequest;

/**
 * Class UserTableController
 */
class UserTableController extends Controller
{
	/**
	 * @var UserRepository
	 */
	protected $users;

	/**
	 * @param UserRepository $users
	 */
	public function __construct(UserRepository $users)
	{
		$this->users = $users;
	}

	/**
	 * @param ManageUserRequest $request
	 * @return mixed
	 */
	public function __invoke(ManageUserRequest $request) {
		return Datatables::of($this->users->getForDataTable($request->get('status'), $request->get('trashed')))
			->editColumn('confirmed', function($user) {
				return $user->confirmed_label;
			})
			->addColumn('roles', function($user) {
				return $user->roles->count() ?
					implode("<br/>", $user->roles->pluck('name')->toArray()) :
					trans('labels.general.none');
			})
			->addColumn('actions', function($user) {
				return $user->action_buttons;
			})
			->withTrashed()
			->make(true);
	}
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Driver;
use App\Models\DriverSchedule;
use Carbon\Carbon;
use Illuminate\Console\Scheduling\Schedule;

/**
 * Class DashboardController
 * @package App\Http\Controllers\Backend
 */
class DashboardController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('backend.dashboard', [
            'scheduledContractsSinceYesterday' => DriverSchedule::whereDate('date', '>=', Carbon::yesterday())->get(),
            'processedContractsSinceYesterday' => DriverSchedule::whereDate('date', '<', Carbon::today())->get(),
            'internalDrivers' => Driver::where('type', 'internal')->get(),
            'externalDrivers' => Driver::where('type', 'external')->get()
        ]);
    }
}

resources/views/backend/activities/edit.blade.php
@extends ('backend.layouts.app')

@section ('title', trans('labels.backend.activities.management') . ' | ' . trans('labels.backend.activities.edit'))

@section('page-header')
    <h1>
        {{ trans('labels.backend.activities.header') }}
        <small>{{ trans('labels.backend.activities.edit') }}</small>
    </h1>
@endsection

@section('content')
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Info</h3>
        </div>
        <div class="box-body">
            <div class="row div col-md-12">
                <table class="table table-striped table-hover">

                    <tr>
                        <th>{{ trans('labels.backend.activities.tabs.content.name') }}</th>
                        <td>{{ $activity->name }}</td>
                    </tr>
                    <tr>
                        <th>{{ trans('labels.backend.activities.tabs.content.type') }}</th>
                        <td>{{ $activity->type }}</td>
                    </tr>
                    <tr>
                        <th>{{ trans('labels.backend.activities.tabs.content.is_planning') }}</th>
                        <td>{!! $activity->plannable !!}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    {{ Form::model($activity, ['route' => ['admin.activities.update', $activity], 'class' => 'form-horizontal', 'role' => 'form', 'method' => 'PATCH']) }}

        <div class="box box-success">
            <div class="box-header with-border">

                <h3 class="box-title">{{ trans('labels.backend.activities.edit') }}</h3>

                <div class="box-tools pull-right">
                    @include('backend.activities.includes.partials.header-buttons')
                </div><!--box-tools pull-right-->
            </div><!-- /.box-header -->

            <div class="box-body">
                <div class="form-group">

                    {{ Form::label('color', trans('validation.attributes.backend.activities.color'), ['class' => 'col-lg-2 control-label']) }}

                    <div class="col-lg-10">
                        <div id="color-picker" class="input-group colorpicker-component">
                            {{ Form::text('color', null, ['class' => 'form-control', 'placeholder' => trans('validation.attributes.backend.activities.color')]) }}
                            <span class="input-group-addon"><i></i></span>
                        </div>

                    </div><!--col-lg-10-->
                </div><!--form control-->

            </div><!-- /.box-body -->
        </div><!--box-->

        <div class="box box-success">
            <div class="box-body">
                <div class="pull-left">
                    {{ link_to_route('admin.activities.index', trans('buttons.general.cancel'), [], ['class' => 'btn btn-danger btn-xs']) }}
                </div><!--pull-left-->

                <div class="pull-right">
                    {{ Form::submit(trans('buttons.general.crud.update'), ['class' => 'btn btn-success btn-xs']) }}
                </div><!--pull-right-->

                <div class="clearfix"></div>
            </div><!-- /.box-body -->
        </div><!--box-->

    {{ Form::close() }}
@stop

@section('after-scripts')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.3.6/css/bootstrap-colorpicker.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/2.3.6/js/bootstrap-colorpicker.min.js"></script>
    <script>
        $('#color-picker').colorpicker({
            format: 'hex'
        });
    </script>
@stop

resources/views/backend/activities/index.blade.php
@extends ('backend.layouts.app')

@section ('title', trans('labels.backend.access.users.management'))

@section('after-styles')
    {{ Html::style("css/backend/plugin/datatables/dataTables.bootstrap.min.css") }}
@stop

@section('page-header')
    <h1>
        {{ trans('labels.backend.activities.title') }}
    </h1>
@endsection

@section('content')
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">{{ trans('labels.backend.activities.header') }}</h3>

            <div class="box-tools pull-right">
                @include('backend.activities.includes.partials.header-buttons')
            </div><!--box-tools pull-right-->
        </div><!-- /.box-header -->

        <div class="box-body">
            <div class="table-responsive">
                <table id="users-table" class="table table-condensed table-hover">
                    <thead>
                        <tr>
                            <th>{{ trans('labels.backend.access.users.table.id') }}</th>
                            <th>{{ trans('labels.backend.activities.table.color') }}</th>
                            <th>{{ trans('labels.backend.activities.table.is_planning') }}</th>
                            <th>{{ trans('labels.backend.activities.table.name') }}</th>
                            <th>{{ trans('labels.backend.activities.table.type') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.created') }}</th>
                            <th>{{ trans('labels.backend.access.users.table.last_updated') }}</th>
                            <th>{{ trans('labels.general.actions') }}</th>
                        </tr>
                    </thead>
                </table>
            </div><!--table-responsive-->
        </div><!-- /.box-body -->
    </div><!--box-->

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">{{ trans('history.backend.recent_history') }}</h3>
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div><!-- /.box tools -->
        </div><!-- /.box-header -->
        <div class="box-body">
            {!! history()->renderType('Activity') !!}
        </div><!-- /.box-body -->
    </div><!--box box-success-->
@stop

@section('after-scripts')
    {{ Html::script("js/backend/plugin/datatables/jquery.dataTables.min.js") }}
    {{ Html::script("js/backend/plugin/datatables/dataTables.bootstrap.min.js") }}

    <script>
        $(function() {
            $('#users-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '{{ route("admin.activities.get") }}',
                    type: 'post'
                },
                columns: [
                    {data: 'id', name: 'transics_activities.id'},
                    {data: 'color', name: 'transics_activities.color'},
                    {data: 'is_planning', name: 'transics_activities.is_planning'},
                    {data: 'name', name: 'transics_activities.name', render: $.fn.dataTable.render.text()},
                    {data: 'type', name: 'transics_activities.type', render: $.fn.dataTable.render.text()},
                    {data: 'created_at', name: 'transics_activities.created_at'},
                    {data: 'updated_at', name: 'transics_activities.updated_at'},
                    {data: 'actions', name: 'actions', searchable: false, sortable: false}
                ],
                order: [[2, "desc"],[0, "asc"]],
                searchDelay: 500
            });
        });
    </script>
@stop

resources/views/backend/activities/show.blade.php
@extends ('backend.layouts.app')

@section ('title', trans('labels.backend.activities.management') . ' | ' . trans('labels.backend.activities.view'))

@section('page-header')
    <h1>
        {{ trans('labels.backend.activities.title') }}
        <small>{{ trans('labels.backend.activities.view') }}</small>
    </h1>
@endsection

@section('content')
    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title">{{ trans('labels.backend.activities.view') }}</h3>

            <div class="box-tools pull-right">
                @include('backend.activities.includes.partials.header-buttons')
            </div><!--box-tools pull-right-->
        </div><!-- /.box-header -->

        <div class="box-body">

            <div role="tabpanel">

                <!-- Nav tabs -->
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active">
                        <a href="#overview" aria-controls="overview" role="tab" data-toggle="tab">{{ trans('labels.backend.access.users.tabs.titles.overview') }}</a>
                    </li>

                    <li role="presentation">
                        <a href="#history" aria-controls="history" role="tab" data-toggle="tab">{{ trans('labels.backend.access.users.tabs.titles.history') }}</a>
                    </li>
                </ul>

                <div class="tab-content">

                    <div role="tabpanel" class="tab-pane mt-30 active" id="overview">
                        @include('backend.activities.tabs.overview')
                    </div><!--tab overview profile-->

                    <div role="tabpanel" class="tab-pane mt-30" id="history">
                        @include('backend.activities.tabs.history')
                    </div><!--tab panel history-->

                </div><!--tab content-->

            </div><!--tab panel-->

        </div><!-- /.box-body -->
    </div><!--box-->
@stop